name: todo_list_finalproj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1  
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.3.4
  provider: ^6.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

