# name: todo_list_finalproj
# description: "A new Flutter project."
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: ^3.5.3

# dependencies:
#   flutter:
#     sdk: flutter
#   firebase_core: ^3.8.1
#   firebase_auth: ^5.3.4
#   cloud_firestore: ^5.5.1
#   speech_to_text: ^7.0.0
#   flutter_local_notifications: ^13.0.0
#   google_fonts: ^3.0.1
#   timezone: ^0.9.0
#   shared_preferences: ^2.0.15
#   provider: ^6.1.2
#   uuid: ^4.5.1
#   sqflite: ^2.4.1
#   file_picker: ^5.2.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0

# flutter:
#   uses-material-design: true
name: todo_list_finalproj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  google_fonts: ^6.2.1
  timezone: ^0.10.0
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  uuid: ^4.5.1
  sqflite: ^2.4.1
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
